apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-gjvz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-gjvz
    app.kubernetes.io/part-of: test-app-837
  name: fbc-sample-repo-gjvz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-gjvz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-gjvz
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-837/fbc-sample-repo-gjvz@sha256:1b2b52b78145b84685898c59ee80cf0c2c20d6fea3468be450c5a182924eb290
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
