apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-fmlx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-use-latest-parent-image-fmlx
    app.kubernetes.io/part-of: test-app-837
  name: e2e-tests-use-latest-parent-image-fmlx
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-fmlx
status:
  loadBalancer: {}
