apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-asuj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-asuj
    app.kubernetes.io/part-of: test-app-837
  name: pip-e2e-test-asuj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-asuj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-asuj
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-837/pip-e2e-test-asuj@sha256:281efa7a5ed0293f31b64cb77d883daa2808e3ab04f73ac8dae3afa272b4f23c
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
