apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-ruyh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-ruyh
    app.kubernetes.io/part-of: test-app-837
  name: devfile-sample-python-basic-ruyh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-ruyh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-ruyh
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-837/devfile-sample-python-basic-ruyh@sha256:f2fbd20c98d75e552c58b6dee0929484c34d0f8c43d3754408f9b8f95b4b33f1
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
